language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t somsubha/frontend -f Docker.dev .

script:
  - docker run -e CI=true somsubha/frontend npm run test

deploy:
  provider: elasticbeanstalk
  region: ap-south-1
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-348661920122"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $ACCESS_KEY
  secret_access_key: "$SECRET_KEY"